services:
  - type: web
    name: bookit
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://mkwbyjejaqwiijdljptw.supabase.co